services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-jwt-backend
    environment:
      JWT_SECRET_KEY: "cambia-esta-clave"
    ports:
      - "8000:8000"
